In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Capstone Data - Supermarket Sales.csv')

# Acess Data

In [ ]:
df

,Invoice ID,Branch,Yangon,Naypyitaw,Mandalay,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
0,750-67-8428,A,1,0,0,Normal,Male,Health and beauty,74.69,7,26.1415,NaN,1/5/2019,13:08,Ewallet,9.1
1,226-31-3081,C,0,1,0,Normal,Male,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,9.6
2,631-41-3108,A,1,0,0,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,7.4
3,123-19-1176,A,1,0,0,Normal,Male,Health and beauty,58.22,8,NaN,489.0480,1/27/2019,8 - 30 PM,Ewallet,8.4
4,373-73-7910,A,1,0,0,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,861-77-0145,C,0,1,0,Member,Male,Electronic accessories,81.97,10,40.9850,860.6850,3/3/2019,14:30,Cash,9.2
1002,479-26-8945,B,0,0,1,Member,Female,Sports and travel,16.49,2,1.6490,34.6290,2/5/2019,11:32,Ewallet,4.6
1003,210-67-5886,C,0,1,0,Member,Female,Health and beauty,98.21,3,14.7315,309.3615,2/5/2019,10:41,Credit card,7.8
1004,227-78-1148,B,0,0,1,Normal,Female,Fashion accessories,72.84,7,25.4940,535.3740,2/15/2019,12:44,Cash,8.4
1005,645-44-1170,A,1,0,0,Member,Male,Home and lifestyle,58.07,9,26.1315,548.7615,1/19/2019,20:07,Ewallet,4.3

# Data set Shap

In [ ]:
df.shape

(1006, 16)

# Check colums data types

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1006 entries, 0 to 1005
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Invoice ID     1006 non-null   object
 1   Branch         1006 non-null   object
 2   Yangon         1006 non-null   int64
 3   Naypyitaw      1006 non-null   int64
 4   Mandalay       1006 non-null   int64
 5   Customer type  1006 non-null   object
 6   Gender         1006 non-null   object
 7   Product line   1006 non-null   object
 8   Unit price     1006 non-null   object
 9   Quantity       1006 non-null   int64
 10  Tax 5%         997 non-null    float64
 11  Total          1003 non-null   float64
 12  Date           1006 non-null   object
 13  Time           1006 non-null   object
 14  Payment        1006 non-null   object
 15  Rating         1006 non-null   float64
dtypes: float64(3), int64(4), object(9)
memory usage: 125.9+ KB

# Check duplicated rows

In [ ]:
df.duplicated().sum()

6

# Check NULL values

In [ ]:
df.isnull().sum()

Invoice ID       0
Branch           0
Yangon           0
Naypyitaw        0
Mandalay         0
Customer type    0
Gender           0
Product line     0
Unit price       0
Quantity         0
Tax 5%           9
Total            3
Date             0
Time             0
Payment          0
Rating           0
dtype: int64

In [ ]:
df[df['Tax 5%'].isnull()]

,Invoice ID,Branch,Yangon,Naypyitaw,Mandalay,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
3,123-19-1176,A,1,0,0,Normal,Male,Health and beauty,58.22,8,NaN,489.0480,1/27/2019,8 - 30 PM,Ewallet,8.4
8,665-32-9167,A,1,0,0,Normal,Male,Health and beauty,36.26,2,NaN,76.1460,1/10/2019,17:15,Credit card,7.2
86,362-58-8315,C,0,1,0,Normal,Male,Fashion accessories,76.52,5,NaN,401.7300,3/25/2019,10:23,Cash,9.9
92,873-51-0671,A,1,0,0,Member,Female,Sports and travel,21.98,7,NaN,161.5530,1/10/2019,16:42,Ewallet,5.1
97,871-39-9221,C,0,1,0,Normal,Female,Electronic accessories,12.45 USD,6,NaN,78.4350,2/9/2019,13:11,Cash,4.1
629,308-39-1707,A,1,0,0,Normal,Female,Fashion accessories,12.09 USD,-1,NaN,12.6945,1/26/2019,18:19,Credit card,8.2
830,237-44-6163,A,1,0,0,Normal,Male,Electronic accessories,10.56 USD,-8,NaN,88.7040,1/24/2019,17:43,Cash,7.6
881,115-38-7388,C,0,1,0,Member,Female,Fashion accessories,10.18 USD,-8,NaN,85.5120,3/30/2019,12:51,Credit card,9.5
903,865-41-9075,A,1,0,0,Normal,Male,Food and beverages,11.53 USD,-7,NaN,84.7455,1/28/2019,17:35,Cash,8.1

In [ ]:
df[df['Total'].isnull()]

,Invoice ID,Branch,Yangon,Naypyitaw,Mandalay,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
0,750-67-8428,A,1,0,0,Normal,Male,Health and beauty,74.69,7,26.1415,NaN,1/5/2019,13:08,Ewallet,9.1
14,829-34-3910,A,1,0,0,Normal,Male,Health and beauty,71.38,10,35.6900,NaN,3/29/2019,19:21,Cash,5.7
37,272-65-1806,A,1,0,0,Normal,Male,Electronic accessories,60.88,9,27.3960,NaN,1/15/2019,17:17,Ewallet,4.7

# Check numircal colums

In [ ]:
df.describe()

,Yangon,Naypyitaw,Mandalay,Quantity,Tax 5%,Total,Rating
count,1006.000000,1006.000000,1006.000000,1006.000000,997.000000,1003.000000,1006.000000
mean,0.338966,0.329026,0.332008,5.469185,15.479682,322.734689,7.056163
std,0.473594,0.470093,0.471168,3.014153,11.728320,245.865964,3.318751
min,0.000000,0.000000,0.000000,-8.000000,0.508500,10.678500,4.000000
25%,0.000000,0.000000,0.000000,3.000000,5.986500,123.789750,5.500000
50%,0.000000,0.000000,0.000000,5.000000,12.227500,254.016000,7.000000
75%,1.000000,1.000000,1.000000,8.000000,22.720500,471.009000,8.500000
max,1.000000,1.000000,1.000000,10.000000,49.650000,1042.650000,97.000000

# Check Quantity column

In [ ]:
# Step 1: Identify rows where 'Quantity' has negative values
negative_quantity = df[df['Quantity'] < 0]

# Display the rows with negative quantities (before cleaning)
print("Rows with negative quantities (before cleaning):")
negative_quantity

Rows with negative quantities (before cleaning):

,Invoice ID,Branch,Yangon,Naypyitaw,Mandalay,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
629,308-39-1707,A,1,0,0,Normal,Female,Fashion accessories,12.09 USD,-1,NaN,12.6945,1/26/2019,18:19,Credit card,8.2
830,237-44-6163,A,1,0,0,Normal,Male,Electronic accessories,10.56 USD,-8,NaN,88.7040,1/24/2019,17:43,Cash,7.6
881,115-38-7388,C,0,1,0,Member,Female,Fashion accessories,10.18 USD,-8,NaN,85.5120,3/30/2019,12:51,Credit card,9.5
903,865-41-9075,A,1,0,0,Normal,Male,Food and beverages,11.53 USD,-7,NaN,84.7455,1/28/2019,17:35,Cash,8.1

# Check Rate  column
## Detect rows with invalid Rate

In [ ]:
# Define the valid range for the 'Rating' column (assuming it's from 1 to 10)
invalid_ratings = df[(df['Rating'] < 1) | (df['Rating'] > 10)]

# Display rows with invalid ratings
print("Rows with invalid ratings:")
invalid_ratings

Rows with invalid ratings:

,Invoice ID,Branch,Yangon,Naypyitaw,Mandalay,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
157,307-85-2293,B,0,0,1,Normal,Male,Home and lifestyle,50.28,5,12.57,263.97,3/7/2019,13:58,Ewallet,97.0

# Check categorical colums

In [ ]:
df['Invoice ID'].value_counts()

Invoice ID
645-44-1170    2
227-78-1148    2
479-26-8945    2
861-77-0145    2
588-01-7461    2
              ..
873-95-4984    1
416-13-5917    1
150-89-8043    1
135-84-8019    1
849-09-3807    1
Name: count, Length: 1000, dtype: int64

In [ ]:
df['Customer type'].value_counts()

Customer type
Normal     515
Member     463
-           27
Memberr      1
Name: count, dtype: int64

In [ ]:
df['Gender'].value_counts()

Gender
Male      525
Female    481
Name: count, dtype: int64

In [ ]:
df['Product line'].value_counts()

Product line
Fashion accessories       179
Food and beverages        175
Electronic accessories    171
Sports and travel         167
Home and lifestyle        161
Health and beauty         153
Name: count, dtype: int64

In [ ]:
df['Payment'].value_counts()

Payment
Ewallet        347
Cash           347
Credit card    312
Name: count, dtype: int64

# Check Time column
## Detect rows with invalid time formats

In [ ]:
# Regex pattern to validate time in 24-hour format (HH:MM)

time_pattern = r'^(?:[01]\d|2[0-3]):[0-5]\d$'

# Detect rows with invalid time formats

invalid_time = df[~df['Time'].str.match(time_pattern, na=False)]

invalid_time

,Invoice ID,Branch,Yangon,Naypyitaw,Mandalay,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
3,123-19-1176,A,1,0,0,Normal,Male,Health and beauty,58.22,8,NaN,489.048,1/27/2019,8 - 30 PM,Ewallet,8.4

# Tidness issues
## `Supermarket Sales` table

##- The issue with the data is that locations (Yangon, Naypyitaw, Mandalay) are represented as columns, which creates redundant columns for each location.


---


# Quality issues

## - Dataset have duplicated rows

## - `Unit price` -  This columns are not in correct data tybe
## - `Quantitiy` -  have nagitive values

##- Two columns containing missing data
### 1.  `Tax 5%` : 9 missing data
### 2.  `Total`  : 3 missing data

##- `Customer type`  column due to inconsistent data entries
### 1- " - "
### 2. " memberr "

##- `Time` column have value is not in  time standared format

##- `Rating` column have value is not in  between 1 and 10

# **Problem**
## Tidness issue
 ### The issue with the data is that locations (Yangon, Naypyitaw, Mandalay) are represented as columns, which creates redundant columns for each location.

# **Code**

In [ ]:
df_melted = pd.melt(df,
                    id_vars=['Invoice ID', 'Branch', 'Customer type', 'Gender', 'Product line',
                             'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date', 'Time',
                             'Payment', 'Rating'],
                    value_vars=['Yangon', 'Naypyitaw', 'Mandalay'],
                    var_name='City', value_name='Presence')

# Filter to keep only rows where 'Presence' is 1
df = df_melted[df_melted['Presence'] == 1].drop(columns=['Presence'])

# Rearrange the columns to make 'City' the third column
df = df[['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender', 'Product line',
                     'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date', 'Time', 'Payment',
                     'Rating']]

# **test**

In [ ]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
0,750-67-8428,A,Yangon,Normal,Male,Health and beauty,74.69,7,26.1415,NaN,1/5/2019,13:08,Ewallet,9.1
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,7.4
3,123-19-1176,A,Yangon,Normal,Male,Health and beauty,58.22,8,NaN,489.0480,1/27/2019,8 - 30 PM,Ewallet,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,5.3
6,355-53-5943,A,Yangon,Normal,Male,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3003,602-16-6955,B,Mandalay,Normal,Female,Sports and travel,76.6,10,38.3000,804.3000,1/24/2019,18:10,Ewallet,6.0
3005,690-01-6631,B,Mandalay,Normal,Male,Fashion accessories,17.49,10,8.7450,183.6450,2/22/2019,18:35,Ewallet,6.6
3008,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,4.4
3014,479-26-8945,B,Mandalay,Member,Female,Sports and travel,16.49,2,1.6490,34.6290,2/5/2019,11:32,Ewallet,4.6
3016,227-78-1148,B,Mandalay,Normal,Female,Fashion accessories,72.84,7,25.4940,535.3740,2/15/2019,12:44,Cash,8.4

# **problem**
## data set have duplicated values

# **Code**

In [ ]:
df.drop_duplicates(inplace=True)

# **Test**

In [ ]:
df.duplicated().sum()

0

# **Problem**
## Unit price column not in correct data tybe

## **Why ?**
### becuse it is object ( have numeric and non-numeric )

##**Check non numeric values**

In [ ]:
# Step 1: Identify the rows that initially contained non-numeric values (e.g., "USD")
non_numeric = df[~df['Unit price'].str.match(r'^\d+\.?\d*$', na=False)]

# Print the original rows containing "USD" or other non-numeric characters
print("Original rows with non-numeric values:")
non_numeric[['Unit price']]

Original rows with non-numeric values:

     Unit price
629   12.09 USD
830   10.56 USD
903   11.53 USD
1103  12.45 USD
1887  10.18 USD

### Step 1: Remove "USD" or other non-numeric characters from the 'Unit price'

In [ ]:
df.loc[non_numeric.index, 'Unit price'] = df.loc[non_numeric.index, 'Unit price'].replace({'[^\d.]': ''}, regex=True)

### Step 2: Convert the 'Unit price' column to float

In [ ]:
# Step 1: Convert the 'Unit price' column to float
df['Unit price'] = pd.to_numeric(df['Unit price'], errors='coerce')

#**Test**

In [ ]:

# Step 3: Check the cleaned values for these specific rows
cleaned_values = df.loc[non_numeric.index, 'Unit price']

# Print the cleaned values to verify that "USD" was removed
print("\nCleaned values for the same rows after removing 'USD':")
cleaned_values

Cleaned values for the same rows after removing 'USD':

629     12.09
830     10.56
903     11.53
1103    12.45
1887    10.18
Name: Unit price, dtype: float64

In [ ]:
df.dtypes

Invoice ID        object
Branch            object
City              object
Customer type     object
Gender            object
Product line      object
Unit price       float64
Quantity           int64
Tax 5%           float64
Total            float64
Date              object
Time              object
Payment           object
Rating           float64
dtype: object

#**Problem**
## Quantity have negative values

In [ ]:
# Step 1: Identify rows where 'Quantity' has negative values
negative_quantity = df[df['Quantity'] < 0]

# Display the rows with negative quantities (before cleaning)
print("Rows with negative quantities (before cleaning):")
negative_quantity

Rows with negative quantities (before cleaning):

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
629,308-39-1707,A,Yangon,Normal,Female,Fashion accessories,12.09,-1,NaN,12.6945,1/26/2019,18:19,Credit card,8.2
830,237-44-6163,A,Yangon,Normal,Male,Electronic accessories,10.56,-8,NaN,88.7040,1/24/2019,17:43,Cash,7.6
903,865-41-9075,A,Yangon,Normal,Male,Food and beverages,11.53,-7,NaN,84.7455,1/28/2019,17:35,Cash,8.1
1887,115-38-7388,C,Naypyitaw,Member,Female,Fashion accessories,10.18,-8,NaN,85.5120,3/30/2019,12:51,Credit card,9.5

#**Code**

In [ ]:

# Step 2: Fix negative quantities by replacing them with absolute values
df.loc[negative_quantity.index, 'Quantity'] = df.loc[negative_quantity.index, 'Quantity'].abs()

# **Test**

In [ ]:

# Step 3: Display the same rows after cleaning
fixed_negative_quantity = df.loc[negative_quantity.index]

print("\nRows with negative quantities (after cleaning):")
fixed_negative_quantity

Rows with negative quantities (after cleaning):

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
629,308-39-1707,A,Yangon,Normal,Female,Fashion accessories,12.09,1,NaN,12.6945,1/26/2019,18:19,Credit card,8.2
830,237-44-6163,A,Yangon,Normal,Male,Electronic accessories,10.56,8,NaN,88.7040,1/24/2019,17:43,Cash,7.6
903,865-41-9075,A,Yangon,Normal,Male,Food and beverages,11.53,7,NaN,84.7455,1/28/2019,17:35,Cash,8.1
1887,115-38-7388,C,Naypyitaw,Member,Female,Fashion accessories,10.18,8,NaN,85.5120,3/30/2019,12:51,Credit card,9.5

#total column have nulls

#**Code**

In [ ]:
# Show rows where 'Total' is null
missing_total = df[df['Total'].isnull()]
missing_total

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
0,750-67-8428,A,Yangon,Normal,Male,Health and beauty,74.69,7,26.1415,NaN,1/5/2019,13:08,Ewallet,9.1
14,829-34-3910,A,Yangon,Normal,Male,Health and beauty,71.38,10,35.6900,NaN,3/29/2019,19:21,Cash,5.7
37,272-65-1806,A,Yangon,Normal,Male,Electronic accessories,60.88,9,27.3960,NaN,1/15/2019,17:17,Ewallet,4.7

In [ ]:
# Fill missing 'Total' values
df['Total'] = df['Total'].fillna(df['Unit price'] * df['Quantity'] + df['Tax 5%'])

In [ ]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
0,750-67-8428,A,Yangon,Normal,Male,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,9.1
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,7.4
3,123-19-1176,A,Yangon,Normal,Male,Health and beauty,58.22,8,NaN,489.0480,1/27/2019,8 - 30 PM,Ewallet,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,5.3
6,355-53-5943,A,Yangon,Normal,Male,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999,552-44-5977,B,Mandalay,Member,Male,Health and beauty,62.00,8,24.8000,520.8000,1/3/2019,19:08,Credit card,6.2
3001,430-53-4718,B,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,15:46,Credit card,8.4
3003,602-16-6955,B,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,1/24/2019,18:10,Ewallet,6.0
3005,690-01-6631,B,Mandalay,Normal,Male,Fashion accessories,17.49,10,8.7450,183.6450,2/22/2019,18:35,Ewallet,6.6
3008,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,4.4

In [ ]:
# Show rows where 'Total' is still null
null_total_after = df[df['Total'].isnull()][['Total']]
print("Null values in 'Total' after cleaning:")
null_total_after

Null values in 'Total' after cleaning:

Empty DataFrame
Columns: [Total]
Index: []

# **problem**

#6-tax 5% column have nan -> calculate the column from total to fill nulls

# **Code**

In [ ]:
# Show rows where 'Tax 5%' is null
null_tax_before = df[df['Tax 5%'].isnull()][['Tax 5%']]
print("Null values in 'Tax 5%' before cleaning:")
print(null_tax_before)

Null values in 'Tax 5%' before cleaning:
      Tax 5%
3        NaN
8        NaN
92       NaN
629      NaN
830      NaN
903      NaN
1092     NaN
1103     NaN
1887     NaN

In [ ]:
df['Tax 5%'] = df['Tax 5%'].fillna(0.05 * df['Unit price'] * df['Quantity'])

In [ ]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
0,750-67-8428,A,Yangon,Normal,Male,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,9.1
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,7.4
3,123-19-1176,A,Yangon,Normal,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8 - 30 PM,Ewallet,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,5.3
6,355-53-5943,A,Yangon,Normal,Male,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999,552-44-5977,B,Mandalay,Member,Male,Health and beauty,62.00,8,24.8000,520.8000,1/3/2019,19:08,Credit card,6.2
3001,430-53-4718,B,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,15:46,Credit card,8.4
3003,602-16-6955,B,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,1/24/2019,18:10,Ewallet,6.0
3005,690-01-6631,B,Mandalay,Normal,Male,Fashion accessories,17.49,10,8.7450,183.6450,2/22/2019,18:35,Ewallet,6.6
3008,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,4.4

In [ ]:
# Show rows where 'Tax 5%' is still null
null_tax_after = df[df['Tax 5%'].isnull()][['Tax 5%']]
print("Null values in 'Tax 5%' after cleaning:")
null_tax_after

Null values in 'Tax 5%' after cleaning:

Empty DataFrame
Columns: [Tax 5%]
Index: []

In [ ]:
df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 3008
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Invoice ID     1000 non-null   object
 1   Branch         1000 non-null   object
 2   City           1000 non-null   object
 3   Customer type  1000 non-null   object
 4   Gender         1000 non-null   object
 5   Product line   1000 non-null   object
 6   Unit price     1000 non-null   float64
 7   Quantity       1000 non-null   int64
 8   Tax 5%         1000 non-null   float64
 9   Total          1000 non-null   float64
 10  Date           1000 non-null   object
 11  Time           1000 non-null   object
 12  Payment        1000 non-null   object
 13  Rating         1000 non-null   float64
dtypes: float64(4), int64(1), object(9)
memory usage: 149.5+ KB

# **Problem**
##- `Customer type`  column due to inconsistent data entries
### 1- " - "
### 2. " memberr "

#Replace " - " in customer type to column "unknown"

In [ ]:
# Replace '-' with 'Unknown' or 'Known' as per your requirement
df['Customer type'] = df['Customer type'].replace('-', 'Unknown')

#Replace "memberr" in customer type to column "member"

In [ ]:
df['Customer type'] = df['Customer type'].replace('Memberr', 'Member')

# **Test**

In [ ]:
df['Customer type'].value_counts()

Customer type
Normal     513
Member     460
Unknown     27
Name: count, dtype: int64

#**problem**
##- `Rating` column have value is not in  between 1 and 10

In [ ]:
# Define the valid range for the 'Rating' column (assuming it's from 1 to 10)
invalid_ratings = df[(df['Rating'] < 1) | (df['Rating'] > 10)]

# Display rows with invalid ratings
print("Rows with invalid ratings:")
invalid_ratings

Rows with invalid ratings:

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
2169,307-85-2293,B,Mandalay,Normal,Male,Home and lifestyle,50.28,5,12.57,263.97,3/7/2019,13:58,Ewallet,97.0

# **Code**

In [ ]:
# Step 1: Mark rows where 'Rating' is 97 (these are the rows to be cleaned)
invalid_ratings_before_cleaning = df[df['Rating'] == 97]
# Step 2: Replace the value 97 with 9.7 in the 'Rating' column
df['Rating'] = df['Rating'].replace(97, 9.7)

# **Test**

In [ ]:
# Step 3: Display only the rows that had '97' and were cleaned
invalid_ratings_after_cleaning = df.loc[invalid_ratings_before_cleaning.index]

print("Rows with invalid ratings after cleaning (replaced 97 with 9.7):")
invalid_ratings_after_cleaning

Rows with invalid ratings after cleaning (replaced 97 with 9.7):

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
2169,307-85-2293,B,Mandalay,Normal,Male,Home and lifestyle,50.28,5,12.57,263.97,3/7/2019,13:58,Ewallet,9.7

#**problem**
##- `Time` column have value is not in  time standared format

In [ ]:
# Step 2: Manually fix the invalid time (assuming the incorrect time is "8 - 30 PM" and it should be "20:30")
df.loc[invalid_time.index, 'Time'] = "20:30"

# Step 3: Display the cleaned row
cleaned_times = df.loc[invalid_time.index]

cleaned_times

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
3,123-19-1176,A,Yangon,Normal,Male,Health and beauty,58.22,8,23.288,489.048,1/27/2019,20:30,Ewallet,8.4

In [ ]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Rating
0,750-67-8428,A,Yangon,Normal,Male,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,9.1
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,7.4
3,123-19-1176,A,Yangon,Normal,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:30,Ewallet,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,5.3
6,355-53-5943,A,Yangon,Normal,Male,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999,552-44-5977,B,Mandalay,Member,Male,Health and beauty,62.00,8,24.8000,520.8000,1/3/2019,19:08,Credit card,6.2
3001,430-53-4718,B,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,15:46,Credit card,8.4
3003,602-16-6955,B,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,1/24/2019,18:10,Ewallet,6.0
3005,690-01-6631,B,Mandalay,Normal,Male,Fashion accessories,17.49,10,8.7450,183.6450,2/22/2019,18:35,Ewallet,6.6
3008,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,4.4

# Export df_clean to a CSV file

In [ ]:
df.to_csv('df_clean(new1).csv', index=False)
print("DataFrame exported successfully to 'df_clean'")

DataFrame exported successfully to 'df_clean'